repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
        language_version: python3.12
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        exclude: "^k8s/"
    -   id: check-toml
    -   id: no-commit-to-branch
    args: ["--branch", "main", "--branch", "master"]

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args: ["--py312-plus"]

-   repo: local
    hooks:
      - id: format
        name: format
        entry: uv run ruff format
        require_serial: true
        language: system
        types: [python]


#-   repo: local
#    hooks:

#    -   id: mypy
#        name: Validate types with MyPy
#        entry: poetry run mypy
#        language: system
#        types: [python]
#        pass_filenames: false
#        args:
#        -   "snowcell_backend"
